### ISSUE TITLE
গেলি? 

### ISSUE THREAD

**Issue by rashomon-gh** [maacpiash/Dante#1]
# গেলি? 
#### গেলি?

**Comment by maacpiash** [comment]
আর কিছু?

**Comment by ShawonAshraf** [comment]
# ভদক্স
## ভদক্স
### ভদক্স
#### ভদক্স
##### ভদক্স

**Comment by maacpiash** [comment]
Am I complicating [this](https://github.com/maacpiash/Dante/blob/master/src/Models/Activity.cs) too much?

**Comment by ShawonAshraf** [comment]
The reaction array is. You sure you can manage that many states on a simple database? It'll be a front end nightmare.

**Comment by maacpiash** [comment]
The problem is, Entity Framework Core does not support collections of primitive types.

**Comment by ShawonAshraf** [comment]
Eh, use ENUMS.

**Comment by maacpiash** [comment]
Same issue with enums :cry:

**Comment by ShawonAshraf** [comment]
What sort of idiotic framework is that?

**Comment by ShawonAshraf** [comment]
Erm I don't know how this sounds but why don't you use [this one?](
https://vapor.codes)
